### PR TITLE
Add apiEndpoint property to config.json

### PR DESCRIPTION
**Pull request by jviotti**
The supervisor needs this property to communicate with the api.

### CODE REVIEW

**Comment by Page-** [comment]
You also need `vpnEndpoint` and `registryEndpoint`

**Comment by jviotti** [comment]
@Page- Where should these point to? Can you give me an example?

**Comment by Page-** [comment]
An example config.json I use in my devenv:

``` json
{
  "applicationId": 1,
  "apiKey": "",
  "userId": 2,
  "username": "page",
  "deviceType": "raspberry-pi2",
  "wifiSsid": "asd",
  "wifiKey": "asd",
  "apiEndpoint": "https:\/\/api.resindev.io",
  "vpnEndpoint": "vpn.resindev.io",
  "appUpdatePollInterval": "60000",
  "listenPort": "48484",
  "mixpanelToken": "",
  "pubnubPublishKey": "",
  "pubnubSubscribeKey": "",
  "registryEndpoint": "registry.resindev.io",
  "files": {
    "network\/settings": "[global]\nOfflineMode=false\n\n[WiFi]\nEnable=true\nTethering=false\n\n[Wired]\nEnable=true\nTethering=false\n\n[Bluetooth]\nEnable=true\nTethering=false",
    "network\/network.config": "[service_home_ethernet]\nType = ethernet\nNameservers = 8.8.8.8,8.8.4.4\n\n[service_home_wifi]\nType = wifi\nName = asd\nPassphrase = asd\nNameservers = 8.8.8.8,8.8.4.4"
  },
  "uuid": "",
  "registered_at": 1441194026428,
  "deviceId": 1
}
```

**Comment by jviotti** [comment]
@Page- Thanks. I'm adding these settings to the default settings object here: https://github.com/resin-io/resin-settings-client/pull/19, which will later be used in `resin-device-config` to provide the urls in `config.json`.

**Pull request merged**
