### PR TITLE
remove legacy wifiSsid and passphrase

### PR DESCRIPTION
**Pull request by shaunmulligan**

### CODE REVIEW

**Comment by petrosagg** [comment]
SGTM

**Comment by Page-** [comment]
SGTM, but @abresas can you check this as well please

**Review by Page- — APPROVED** [review]

**Comment by Page-** [comment]
@petrosagg this will break your recent img-maker PR for network-manager stuff right?

**Comment by shaunmulligan** [comment]
@petrosagg or @Page- I fixed the conflicts, can we merge this or throw it away. I just would like those legacy keys to disappear

**Comment by Page-** [comment]
I think @petrosagg may have started using them for the network manager stuff, @petrosagg?

**Comment by petrosagg** [comment]
@Page- no I'm not using them. We can remove them

**Comment by zvin** [comment]
PR updated, please review again @Page-

**Comment by zvin** [comment]
replaced by https://github.com/resin-io/resin-image-maker/pull/51

**Pull request closed without merging**
