### PR TITLE
Allow the Pubnub keys to be empty if required.

### PR DESCRIPTION
**Pull request by hedss**
Supports target environments that are not network connected.

Connects-to: #53
Change-type: patch
---- Autogenerated Waffleboard Connection: Connects to #53

### CODE REVIEW

**Review by pimterry — CHANGES_REQUESTED** [review]
We've got tests in here covering most of the important configuration validation, can you add a test in https://github.com/resin-io-modules/resin-device-config/blob/master/tests/config.spec.coffee that checks that this does what you're expecting?

**Comment by hedss** [comment]
It looks like the last [PR](https://github.com/resin-io-modules/resin-device-config/pull/49/files) may not have included the changes for the built JS, as building for this PR has included it. Would like confirmation that this is now correct (@LucianBuzzo).

**Review by pimterry — APPROVED** [review]
Good spot on the rebuilt source, end result looks sensible to me. I wonder if maybe actually the pubnub keys should be nullable, rather than using empty strings for this? Really though whatever's easier for you in the API & supervisor is FBM.

**Comment by hedss** [comment]
@pimterry Yeah, I had considered just totally removing the keys to start with, but I think that'll cause an issue with the API, so I've left as is for the moment. Thanks!

**Pull request merged**
